# Notebook for reproducing the neutrino masses and PMNS from data inside GitHub

In [1]:
#Requires numpy and pandas
import pandas as pd
import numpy as np

# Read dataframes with the data. Please adapt your own paths. We demonstrate from the previous data (which is the Data_v2 in the GitHub)

In [2]:
#Note: The path can be for the entire data set, or just to the best fit points. It will work for both
Path_to_files = "/home/felipe/Desktop/New_data/Upsilon_corrected/To_GItHub/Leptoquark-project---Data/Data_v2"

df_1 = pd.read_csv('{}/Angles.csv'.format(Path_to_files), sep=',')
df_2 = pd.read_csv('{}/Couplings.csv'.format(Path_to_files), sep=',')
df_3 = pd.read_csv('{}/SM_pars.csv'.format(Path_to_files), sep=',')
df_4 = pd.read_csv('{}/Flavour_obs.csv'.format(Path_to_files), sep=',')

# This was not explained in the main text (hence the confusion). In the scan, we have used generic form of the $U_{d, R}$ matrix (right-handed down-type quark mixing).

# This matrix is non-physical and can be absorved in the definition of the $\Omega$ matrix, hence why in the initial version we decided to omit it. However, to properly reproduce the results, one needs this matrix so to rotate the $\Omega$ to the physical basis. Angles for the right mixing are already inside the .csv files. This is how to properly do it.

# The new data from Data_v3 no longer requires this

In [3]:
def PMNS(a13, a23, a12, dCP):
    
    """
    Determine the experimental PMNS matrix, based on the angles. PDG parametrization
    
    Inputs:
        -> a13: Angle between 1 and 3 lepton states
        -> a23: Angle between 2 and 2 lepton states
        -> a12: Angle between 1 and 2 lepton states
        -> dCP: CP violating phase
        
    There is numerical errors when picking dCP = 180. It prints out a non-zero imaginary part. It is very small,
    of the order O(1e-16), but causes errors when trying to find solutions
    A quick hack is added to make Exp(-i*180º) = -1
    
    Additional info: https://stackoverflow.com/questions/59021598/numpy-precision-with-exponentials-of-imaginary-numbers
    """

    if dCP == 180:
        
        ad13 = np.deg2rad(a13)
        ad23 = np.deg2rad(a23)
        ad12 = np.deg2rad(a12)
        ddCP = np.deg2rad(dCP)
        Exp1 = np.round(np.exp(-1j*ddCP))
        Exp2 = np.round(np.exp(+1j*ddCP))


        R1 = np.array([[1,0,0], [0,np.cos(ad23),np.sin(ad23)], [0,-np.sin(ad23),np.cos(ad23)]])
        R2 = np.array([[np.cos(ad13), 0, np.sin(ad13)*Exp1], [0,1,0], [-np.sin(ad13)*Exp2, 0, np.cos(ad13)]])
        R3 = np.array([[np.cos(ad12), np.sin(ad12), 0], [-np.sin(ad12), np.cos(ad12), 0], [0,0,1]])
    
    else:
        
        ad13 = np.deg2rad(a13)
        ad23 = np.deg2rad(a23)
        ad12 = np.deg2rad(a12)
        ddCP = np.deg2rad(dCP)

        R1 = np.array([[1,0,0], [0,np.cos(ad23),np.sin(ad23)], [0,-np.sin(ad23),np.cos(ad23)]])
        R2 = np.array([[np.cos(ad13), 0, np.sin(ad13)*np.exp(-1j*ddCP)], [0,1,0], [-np.sin(ad13)*np.exp(1j*ddCP), 0, np.cos(ad13)]])
        R3 = np.array([[np.cos(ad12), np.sin(ad12), 0], [-np.sin(ad12), np.cos(ad12), 0], [0,0,1]])
        
    Vpmns = R1 @ R2 @ R3
    
    return Vpmns

def CKM (s12, s13, s23, d):
    
    """
    Determine the experimental CKM matrix, based on the standard parameterization
    
    Inputs:
        -> s12: sine of the angle between 1 and 2 quark states
        -> s13: sine of the angle between 1 and 3 quark states
        -> s23: sine of the angle between 2 and 3 quark states
        -> d: CP violating phase
    """
    
    c12 = np.sqrt(1 - s12**2)
    c13 = np.sqrt(1 - s13**2)
    c23 = np.sqrt(1 - s23**2)
    
    R1 = np.array([[1,0,0],[0,c23,s23],[0,-s23,c23]])
    R2 = np.array([[c13,0,s13*np.exp(-1j*d)],[0,1,0],[-s13*np.exp(1j*d),0,c13]])
    R3 = np.array([[c12,s12,0],[-s12,c12,0],[0,0,1]])
    
    Vckm = R1 @ R2 @ R3
    
    return Vckm

def U_dR(a13v, a23v, a12v):
    
    """
    Determine the right down quark mixing matrix
    
    Inputs:
        -> a13v: Angle between 1 and 3 quark states
        -> a23v: Angle between 2 and 2 quark states
        -> a12v: Angle between 1 and 2 quark states
    """
    
    R1v = np.array([[1,0,0], [0, np.cos(a23v), np.sin(a23v)], [0, -np.sin(a23v), np.cos(a23v)]])
    R2v = np.array([[np.cos(a13v), 0, np.sin(a13v)], [0,1,0], [-np.sin(a13v), 0, np.cos(a13v)]])
    R3v = np.array([[np.cos(a12v), np.sin(a12v), 0], [-np.sin(a12v), np.cos(a12v), 0], [0,0,1]])
    
    UdR = R1v @ R2v @ R3v
    
    return UdR

#Neutrino one-loop mass formula. Corresponds to equation (5) in the main text
def Neutrino_oneloop(i, j, Omega, Theta, VCKM, v, a1, md, mS1, mS2):
    
    """
    Computes the loop function for the neutrino mass matrix. Takes as input
    the Yukawa matrices, Omega and Theta, the CKM mixing matrix, the cubic term
    a1, the vaccuum expectation value, the leptoquark masses (mS1 and mS2) and the
    down-type quark masses.
    
    """
    
    Cte = (3*alpha1*v)/(16*np.sqrt(2)*(mS2**2 - mS1**2)*np.pi**2)*np.log(mS2**2/mS1**2)
    
    F = Cte*sum(md[a]*VCKM[a,m]*(Theta[i][m]*Omega[j][a] + Theta[j][m]*Omega[i][a]) for m in range(3) for a in range(3)) 
    
    return F

def eigen(A):
    
    """
    Computes the eigenvalues and eigenvectors, and orders the output
    from smallest to hightest.
    
    Returns a tuple with the eigenvalues (first position) and eigenvectors
    (second position)
    
    Example use: Out_eigvalues, Output_eigvectors = eigen(Matrix)
    
    """
    
    eigenValues, eigenVectors = np.linalg.eig(A)
    idx = np.argsort(np.abs(eigenValues))
    eigenValues = np.abs(eigenValues[idx])
    eigenVectors = eigenVectors[:,idx].T
    return (eigenValues, eigenVectors)


# Calculating the neutrino masses and mixing. Please note that charged leptons are always diagonal! 

In [4]:
#It will pick a random point from the dataframe
#Note: If you are reading only the best fit points, then there is only point inside the dataframes,
#hence, it will always pick that index and not a random one 
loc = np.random.randint(0, len(df_1))

UdR = U_dR(a13v = df_1['a13R'].iloc[loc], a23v = df_1['a23R'].iloc[loc], a12v = df_1['a12R'].iloc[loc])
VCKM = CKM (s12 = df_1['s12q'].iloc[loc], s13 = df_1['s13q'].iloc[loc], s23 = df_1['s23q'].iloc[loc], d = df_1['DqCP'].iloc[loc])
alpha1 = df_2['a1'].iloc[loc]
#Note:
# df_2 contains input masses (mS1 and mS2)
# df_3 contains the masses as calculated in SPheno (mSS1 and mSS2)
# There is a difference between the masses of both files due to a initial bug in the implementation
# Either way, using one or the other seems to still give correct neutrino masses (although some points are slightly off)
# Additionally, the new data from the Data_v3 no longer suffers from this bug
mS1 = df_2['mS1'].iloc[loc]
mS2 = df_2['mS2'].iloc[loc]
v = df_3['v'].iloc[loc]
md = np.array([df_3['md'].iloc[loc], df_3['ms'].iloc[loc], df_3['mb'].iloc[loc]])

Theta = np.array([[complex(df_2['Theta11'].iloc[loc]), complex(df_2['Theta12'].iloc[loc]), complex(df_2['Theta13'].iloc[loc])],
                  [complex(df_2['Theta21'].iloc[loc]), complex(df_2['Theta22'].iloc[loc]), complex(df_2['Theta23'].iloc[loc])],
                  [complex(df_2['Theta31'].iloc[loc]), complex(df_2['Theta32'].iloc[loc]), complex(df_2['Theta33'].iloc[loc])]])

Omega = np.array([[complex(df_2['Omega11'].iloc[loc]), complex(df_2['Omega12'].iloc[loc]), complex(df_2['Omega13'].iloc[loc])],
                  [complex(df_2['Omega21'].iloc[loc]), complex(df_2['Omega22'].iloc[loc]), complex(df_2['Omega23'].iloc[loc])],
                  [complex(df_2['Omega31'].iloc[loc]), complex(df_2['Omega32'].iloc[loc]), complex(df_2['Omega33'].iloc[loc])]])

Omega_physical = Omega @ UdR.T

#Calculate the neutrino mass matrix
Mnu11 = Neutrino_oneloop(i=0, j = 0, Omega = Omega_physical, Theta = Theta, VCKM = VCKM, v = v, a1 = alpha1, md = md, mS1 = mS1, mS2 = mS2)
Mnu12 = Neutrino_oneloop(i=0, j = 1, Omega = Omega_physical, Theta = Theta, VCKM = VCKM, v = v, a1 = alpha1, md = md, mS1 = mS1, mS2 = mS2)
Mnu13 = Neutrino_oneloop(i=0, j = 2, Omega = Omega_physical, Theta = Theta, VCKM = VCKM, v = v, a1 = alpha1, md = md, mS1 = mS1, mS2 = mS2)
Mnu21 = Neutrino_oneloop(i=1, j = 0, Omega = Omega_physical, Theta = Theta, VCKM = VCKM, v = v, a1 = alpha1, md = md, mS1 = mS1, mS2 = mS2)
Mnu22 = Neutrino_oneloop(i=1, j = 1, Omega = Omega_physical, Theta = Theta, VCKM = VCKM, v = v, a1 = alpha1, md = md, mS1 = mS1, mS2 = mS2)
Mnu23 = Neutrino_oneloop(i=1, j = 2, Omega = Omega_physical, Theta = Theta, VCKM = VCKM, v = v, a1 = alpha1, md = md, mS1 = mS1, mS2 = mS2)
Mnu31 = Neutrino_oneloop(i=2, j = 0, Omega = Omega_physical, Theta = Theta, VCKM = VCKM, v = v, a1 = alpha1, md = md, mS1 = mS1, mS2 = mS2)
Mnu32 = Neutrino_oneloop(i=2, j = 1, Omega = Omega_physical, Theta = Theta, VCKM = VCKM, v = v, a1 = alpha1, md = md, mS1 = mS1, mS2 = mS2)
Mnu33 = Neutrino_oneloop(i=2, j = 2, Omega = Omega_physical, Theta = Theta, VCKM = VCKM, v = v, a1 = alpha1, md = md, mS1 = mS1, mS2 = mS2)
Mnu = np.array([[Mnu11, Mnu12, Mnu13],[Mnu21, Mnu22, Mnu23],[Mnu31, Mnu32, Mnu33]])

Mnu_diag, UPMNS = eigen(Mnu)

print("Neutrino masses: \n\n", Mnu_diag)
print("PMNS mixing matrix: \n\n", np.abs(UPMNS))

#PMNS and mass difference conditions. Cond_PMNS must be true
#3 sigma ranges !
Cond_PMNS = ((0.801 <= np.round(np.abs(UPMNS[0,0]),3) <= 0.845) and \
                    (0.513 <= np.round(np.abs(UPMNS[0,1]),3) <= 0.579) and \
                    (0.144 <= np.round(np.abs(UPMNS[0,2]),3) <= 0.156) and \
                    (0.244 <= np.round(np.abs(UPMNS[1,0]),3) <= 0.499) and \
                    (0.505 <= np.round(np.abs(UPMNS[1,1]),3) <= 0.693) and \
                    (0.631 <= np.round(np.abs(UPMNS[1,2]),3) <= 0.768) and \
                    (0.272 <= np.round(np.abs(UPMNS[2,0]),3) <= 0.518) and \
                    (0.471 <= np.round(np.abs(UPMNS[2,1]),3) <= 0.669) and \
                    (0.623 <= np.round(np.abs(UPMNS[2,2]),3) <= 0.761) and \
                    (np.round(((Mnu_diag[1]*1e9)**2 - (Mnu_diag[0]*1e9)**2),7) > (7.42 - 3*0.20)*1e-5) and \
                    (np.round(((Mnu_diag[1]*1e9)**2 - (Mnu_diag[0]*1e9)**2),7) < (7.42 + 3*0.20)*1e-5) and \
                    (np.round(((Mnu_diag[2]*1e9)**2 - (Mnu_diag[1]*1e9)**2),8) > (2.510 - 3*0.027)*1e-3) and \
                    (np.round(((Mnu_diag[2]*1e9)**2 - (Mnu_diag[1]*1e9)**2),8) < (2.510 + 3*0.027)*1e-3))
print("\n")
print("PMNS and mass conditions:", Cond_PMNS)

Neutrino masses: 

 [1.68501935e-17 8.37610034e-12 5.06060619e-11]
PMNS mixing matrix: 

 [[0.82393995 0.54667755 0.14921999]
 [0.31830091 0.66433078 0.67627593]
 [0.46883631 0.5097139  0.72137664]]


PMNS and mass conditions: True


# As one can see, the correct masses and PMNS mixing is reproduced from the data provided in the GitHub page